# Use an official Nginx image as a base
FROM nginx:alpine

# Copy the static website files to the Nginx html directory
COPY . /usr/share/nginx/html

# Expose port 80 to be able to access the website
EXPOSE 80

# The default command to run when the container starts
CMD ["nginx", "-g", "daemon off;"]