services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: 
      context: ./backend
    container_name: adres_app
    env_file:
      - ./backend/.env
    ports:
      - '8000:88'
    restart: "no"
