# 
FROM python:3.10-alpine

# ENV DATABASE = adres.db
# ENV ACQUIS_TABLE = acquisitions
# ENV RECORDS_TABLE = records
# ENV HOST = localhost
# ENV PORT=80

# 
WORKDIR /backend

# 
COPY ./requirements.txt /app/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# 
COPY . ./

EXPOSE 8000

# 
CMD ["fastapi", "run", "main.py", "--host=0.0.0.0", "--port", "88"]
# CMD ["fastapi", "run", "app/app/api.py", "--port", "80"]